# 実行モード: single または batch
mode=batch

# single モード時
single.input=src/test/resources/wazahyo.apib
single.output=target/openapi.yaml

# batch モード時
batch.inputDir=input
batch.outputDir=output
batch.recursive=false
